// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OtenTool.PostmanCore.Contexts;

#nullable disable

namespace OtenTool.PostmanCore.Migrations
{
    [DbContext(typeof(PostmanContext))]
    [Migration("20241203205739_Migration2")]
    partial class Migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TreeItemPropertyId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int?>("tTreeItemPropertyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.HasIndex("TreeItemPropertyId");

                    b.HasIndex("tTreeItemPropertyId");

                    b.ToTable("tHeaders");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.ToTable("tProjects");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tTreeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequest")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectItemId");

                    b.ToTable("tTreeItems");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tTreeItemProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("TreeItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.HasIndex("TreeItemId");

                    b.ToTable("tTreeItemProperties");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.ToTable("tUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedId = 1,
                            IsDeleted = false,
                            Mail = "oten@gmail.com",
                            Password = "admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tHeader", b =>
                {
                    b.HasOne("OtenTool.PostmanCore.Models.tUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtenTool.PostmanCore.Models.tTreeItem", "t_TreeItem")
                        .WithMany()
                        .HasForeignKey("TreeItemPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtenTool.PostmanCore.Models.tTreeItemProperty", null)
                        .WithMany("t_Headers")
                        .HasForeignKey("tTreeItemPropertyId");

                    b.Navigation("CreatedUser");

                    b.Navigation("t_TreeItem");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tProject", b =>
                {
                    b.HasOne("OtenTool.PostmanCore.Models.tUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tTreeItem", b =>
                {
                    b.HasOne("OtenTool.PostmanCore.Models.tUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtenTool.PostmanCore.Models.tTreeItem", "t_TreeItem")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("OtenTool.PostmanCore.Models.tProject", "t_Project")
                        .WithMany()
                        .HasForeignKey("ProjectItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("t_Project");

                    b.Navigation("t_TreeItem");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tTreeItemProperty", b =>
                {
                    b.HasOne("OtenTool.PostmanCore.Models.tUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtenTool.PostmanCore.Models.tTreeItem", "t_TreeItem")
                        .WithMany("tTreeItemProperties")
                        .HasForeignKey("TreeItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("t_TreeItem");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tUser", b =>
                {
                    b.HasOne("OtenTool.PostmanCore.Models.tUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tTreeItem", b =>
                {
                    b.Navigation("tTreeItemProperties");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tTreeItemProperty", b =>
                {
                    b.Navigation("t_Headers");
                });
#pragma warning restore 612, 618
        }
    }
}
