// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OtenTool.PostmanCore.Contexts;

#nullable disable

namespace OtenTool.PostmanCore.Migrations
{
    [DbContext(typeof(PostmanContext))]
    [Migration("20241209202538_Migration3")]
    partial class Migration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.ToTable("tProjects");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tProjectUserMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("tProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("t_UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.HasIndex("tProjectId");

                    b.HasIndex("t_UserId");

                    b.ToTable("tProjectUserMaps");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.ToTable("tRequestItems");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tTreeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequest")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("RequestItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectItemId");

                    b.HasIndex("RequestItemId");

                    b.ToTable("tTreeItems");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.ToTable("tUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedId = 1,
                            IsDeleted = false,
                            Mail = "oten@gmail.com",
                            Password = "admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tProject", b =>
                {
                    b.HasOne("OtenTool.PostmanCore.Models.tUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tProjectUserMap", b =>
                {
                    b.HasOne("OtenTool.PostmanCore.Models.tUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtenTool.PostmanCore.Models.tProject", "tProject")
                        .WithMany()
                        .HasForeignKey("tProjectId");

                    b.HasOne("OtenTool.PostmanCore.Models.tUser", "t_User")
                        .WithMany()
                        .HasForeignKey("t_UserId");

                    b.Navigation("CreatedUser");

                    b.Navigation("tProject");

                    b.Navigation("t_User");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tRequestItem", b =>
                {
                    b.HasOne("OtenTool.PostmanCore.Models.tUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tTreeItem", b =>
                {
                    b.HasOne("OtenTool.PostmanCore.Models.tUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtenTool.PostmanCore.Models.tTreeItem", "t_TreeItem")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("OtenTool.PostmanCore.Models.tProject", "t_Project")
                        .WithMany("t_TreeItems")
                        .HasForeignKey("ProjectItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtenTool.PostmanCore.Models.tRequestItem", "t_RequestItem")
                        .WithMany()
                        .HasForeignKey("RequestItemId");

                    b.Navigation("CreatedUser");

                    b.Navigation("t_Project");

                    b.Navigation("t_RequestItem");

                    b.Navigation("t_TreeItem");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tUser", b =>
                {
                    b.HasOne("OtenTool.PostmanCore.Models.tUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");
                });

            modelBuilder.Entity("OtenTool.PostmanCore.Models.tProject", b =>
                {
                    b.Navigation("t_TreeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
